---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
   namespace: admintestchainorg1
   name: cli
spec:
  replicas: 1
  selector:
    matchLabels:
        app: cli
  template:
    metadata:
      labels:
       app: cli
    spec:
      containers:
        - name: cli
          image: hyperledger/fabric-tools:1.4.1
          env:
          - name: CORE_VM_ENDPOINT
            value: "unix:///host/var/run/docker.sock"
          - name: GOPATH
            value: "/opt/gopath"
          - name: FABRIC_LOGGING_SPEC
            value: "INFO"
          - name: CORE_PEER_TLS_ENABLED
            value: "true"
          - name: CORE_PEER_PROFILE_ENABLED
            value: "true"
          - name: CORE_PEER_TLS_CERT_FILE
            value: "/etc/hyperledger/fabric/tls/server.crt"
          - name: CORE_PEER_TLS_KEY_FILE
            value: "/etc/hyperledger/fabric/tls/server.key"
          - name: CORE_PEER_TLS_ROOTCERT_FILE
            value: "/etc/hyperledger/fabric/tls/ca.crt"
          - name: CORE_PEER_ID
            value: "cli"
          - name: CORE_PEER_ADDRESS
            value: "peer0.admintestchainorg1:7051"
          - name: CORE_PEER_LOCALMSPID
            value: "Org1MSP"
          - name: CORE_PEER_MSPCONFIGPATH
            value: "/etc/hyperledger/fabric/msp"
          workingDir: /etc/hyperledger
          command: ["/bin/bash", "-c", "--"]
          args: ["while true; do sleep 30; done;"]
          volumeMounts:
           - mountPath: /host/var/run
             name: run
           - mountPath: /etc/hyperledger/fabric/msp
             name: certificate
             subPath: crypto-config/peerOrganizations/admintestchainorg1/users/Admin@admintestchainorg1/msp
           - mountPath: /etc/hyperledger/fabric/tls
             name: certificate
             subPath: crypto-config/peerOrganizations/admintestchainorg1/peers/peer0.admintestchainorg1/tls
           - mountPath: /etc/hyperledger/channel-artifacts
             name: certificate
             subPath: channel-artifacts
           - mountPath: /etc/hyperledger/crypto-config
             name: certificate
             subPath: crypto-config
      volumes:
        - name: certificate
          persistentVolumeClaim:
              claimName: admintestchainorg1-pv
        - name: run
          hostPath:
            path: /var/run

