---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  namespace: admintestchainorderer
  name: orderer0-admintestchainorderer
spec:
  selector:
    matchLabels:
        app: hyperledger
        role: orderer
        org: admintestchainorderer
        orderer-id: orderer0
  replicas: 1
  template:
    metadata:
      labels:
        app: hyperledger
        role: orderer
        org: admintestchainorderer
        orderer-id: orderer0
    spec:
      containers:
      - name: orderer0-admintestchainorderer
        image: hyperledger/fabric-orderer:1.4.1
        env:
        - name: FABRIC_LOGGING_SPEC
          value: "INFO"
        - name: ORDERER_GENERAL_LISTENADDRESS
          value: "0.0.0.0"
        - name: ORDERER_GENERAL_GENESISMETHOD
          value: "file"
        - name: ORDERER_GENERAL_GENESISFILE
          value: "/var/hyperledger/orderer/orderer.genesis.block"
        - name: ORDERER_GENERAL_LOCALMSPID
          value: "OrdererMSP"
        - name: ORDERER_GENERAL_LOCALMSPDIR
          value: "/var/hyperledger/orderer/msp"
        - name: ORDERER_GENERAL_TLS_ENABLED
          value: "true"
        - name: ORDERER_GENERAL_TLS_PRIVATEKEY
          value: "/var/hyperledger/orderer/tls/server.key"
        - name: ORDERER_GENERAL_TLS_CERTIFICATE
          value: "/var/hyperledger/orderer/tls/server.crt"
        - name: ORDERER_GENERAL_TLS_ROOTCAS
          value: "[/var/hyperledger/orderer/tls/ca.crt]"
        - name: ORDERER_KAFKA_VERBOSE
          value: "true"
        - name: ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY
          value: "/var/hyperledger/orderer/tls/server.key"
        - name: ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE
          value: "/var/hyperledger/orderer/tls/server.crt"
        - name: ORDERER_GENERAL_CLUSTER_ROOTCAS
          value: "[/var/hyperledger/orderer/tls/ca.crt]"
        workingDir: /opt/gopath/src/github.com/hyperledger/fabric
        ports:
         - containerPort: 7050
        command: ["orderer"]
        volumeMounts:
         - mountPath: /var/hyperledger/orderer/msp
           name: certificate
           subPath: crypto-config/ordererOrganizations/admintestchainorderer/orderers/orderer0.admintestchainorderer/msp
         - mountPath: /var/hyperledger/orderer/tls
           name: certificate
           subPath: crypto-config/ordererOrganizations/admintestchainorderer/orderers/orderer0.admintestchainorderer/tls
         - mountPath: /var/hyperledger/orderer/orderer.genesis.block
           name: certificate
           subPath: channel-artifacts/genesis.block
         - mountPath: /var/hyperledger/production/orderer
           name: ordererdata
           subPath: orderer0.admintestchainorderer
      volumes:
       - name: certificate
         persistentVolumeClaim:
             claimName: admintestchainorderer-pv
       - name: ordererdata
         persistentVolumeClaim:
             claimName: admintestchainorderer-pvdata

---
apiVersion: v1
kind: Service
metadata:
  name: orderer0
  namespace: admintestchainorderer
spec:
 selector:
   app: hyperledger
   role: orderer
   orderer-id: orderer0
   org: admintestchainorderer
 type: NodePort
 ports:
   - name: endpoint
     protocol: TCP
     port: 7050
     targetPort: 7050
#     nodePort: 30050

