NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.admintestchainorg1-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.admintestchainorg1-cert.pem
    OrganizationalUnitIdentifier: peer
